# Generated by Django 6.0.6 on 2026-06-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empoyee',
            new_name='Employee',
        ),
    ]
